services:
  survey-api:
    container_name: survey-api
    restart: always
    image: node:24
    working_dir: /usr/api/survey-api
    command: bash -c "corepack enable && pnpm i --prod --frozen-lockfile --ignore-scripts && pnpm debug"
    volumes:
      - ./dist/:/usr/api/survey-api/dist/
      - ./package.json:/usr/api/survey-api/package.json
      - ./pnpm-lock.yaml:/usr/api/survey-api/pnpm-lock.yaml
    ports:
      - 5050:5050
      - 9222:9222
    depends_on:
      - mongodb
    networks:
      - survey-network

  mongodb:
    image: mongo:8.2
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secretpassword
    volumes:
      - mongo-data:/data/db
    networks:
      - survey-network

volumes:
  mongo-data:

networks:
  survey-network:
    driver: bridge
